---
# tasks file for mx
- name: Install mx dependencies
  dnf:
    name:
      - git
      - python3
      - binutils
      - make
      - gcc
      - file
      - diffutils
      - gcc-c++
    state: latest

- name: Download mx
  get_url:
    url: "https://github.com/graalvm/mx/tarball/{{ mx_version }}"
    dest: /tmp/mx.tar.gz
  register: mx_archive

- name: Make mx directory
  file:
    path: "{{ mx_path }}"
    state: directory

- name: Extract mx
  unarchive:
    remote_src: yes
    src: "{{ mx_archive.dest }}"
    dest: "{{ mx_path }}"
    extra_opts:
    - --strip-components=1

- name: Add mx to $PATH and set MX_PYTHON
  copy:
    dest: /etc/profile.d/mx.sh
    content: |
      export PATH={{ mx_path }}:$PATH
      export MX_PYTHON=python3
