---
- name: Setup machine for mandrel-packaging
  hosts: all
  vars:
    configuration: mandrel20.1-openjdk
    mx_path: /opt/mx
    mandrel_path: /tmp/mandrel
    mandrel_repo: https://github.com/graalvm/mandrel.git
    jdk_path: /opt/jdk


  pre_tasks:
    - name: Include variables for configuration
      include_vars:
        file: "configurations/{{ configuration }}.yml"
    - name: Install core dependencies
      dnf:
        name: tar
        state: latest

  roles:
    - jdk
    - mx
    - maven

  tasks:
    - name: Clone mandrel repository
      git:
        repo: "{{ mandrel_repo }}"
        dest: "{{ mandrel_path }}"
        version: "{{ mandrel_version }}"
        depth: 1
    - name: Copy build.java
      copy:
        src: "{{ playbook_dir }}/../src/"
        dest: "/root/src/"
    - name: Set welcome message
      copy:
        dest: /etc/profile.d/welcome.sh
        content: |
          cat << EOF
                  __  ___                __          __
                 /  |/  /___ _____  ____/ /_______  / /
                / /|_/ / __ \`/ __ \/ __  / ___/ _ \/ /
               / /  / / /_/ / / / / /_/ / /  /  __/ /
              /_/  /_/\__,_/_/ /_/\__,_/_/   \___/_/

          To build locally:
            java -ea /root/src/build.java --install --version 20.1.0.redhat-00001 --verbose

          To build with a maven proxy:
            java -ea /root/src/build.java --install --version 20.1.0.redhat-00001 --maven-proxy https://repo1.maven.org/maven2/ --verbose

          To use an alternative maven local repository:"
            java -ea /root/src/build.java --install --version 20.1.0.redhat-00001 --maven-local-repository /tmp/.m2/repository --verbose

          To override dependencies:
            java -ea /root/src/build.java --install --version 20.1.0.redhat-00001 --dependencies \\
                id=ASM_7.1,version=7.1.0.redhat-00001,sha1=41bc48bf913569bd001cc132624f811d91004af4,sourceSha1=8c938bc977786f0f3964b394e28f31e726769bac \\
                id=...,version=...,sha1=...

          To deploy:
            java -ea /root/src/build.java --deploy --version 20.1.0.redhat-00001 --maven-repo-id abc --maven-url http://1.2.3.4 --verbose

          EOF
