name: Mark stale issues and PRs

on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/**
  schedule:
  - cron: '0 3 * * *'

jobs:
  mark-stale-issues-and-prs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue appears to be stale because it has been open 30 days with no activity. This issue will be closed in 7 days unless `Stale` label is removed or a new comment is made.'
        stale-pr-message: 'This PR appears to be stale because it has been open 30 days with no activity. This PR will be closed in 7 days unless `Stale` label is removed or a new comment is made.'
        days-before-stale: 30
        days-before-close: 7
